[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
placebo = "PROGRAM_ID_PLACEHOLDER"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = ".wallet/id.json"



[scripts]
test = "yarn test"