[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
placebo = "DEdLFqehJ6knPRqEYfJkhaNXowbDNxivZvqRwvsixd6L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet ="/home/rgmelvin/Projects/cabrillo/placebo/.ledger/wallets/test-user.json"



[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


